ORG 1000H
CAR_VIEJO DB "a"
CAR_NUEVO DB "e"
PUNTO DB "."
MSJ_ING DB "INGRESE MENSAJE: "
MSJ_SI DB "SE SUSTITUYERON CARACTERES: "
MSJ_NO DB "NO SE SUSTITUYERON CARACTERES"
MSJ DB ?

ORG 3000H
REEMPLAZAR:
MOV CH, [BX]
CMP CH, AH
JNZ SIGUE
  MOV BYTE PTR[BX], AL
  MOV DL, 1
SIGUE: INC BX
  DEC CL
  JNZ REEMPLAZAR
RET

ORG 2000H
MOV BX, OFFSET MSJ_ING
MOV AL, OFFSET MSJ_SI - OFFSET MSJ_ING
INT 7
MOV CL, 0
MOV DH, PUNTO
MOV BX, OFFSET MSJ
INT 6
LEER: CMP BYTE PTR[BX], DH
JNZ SEGUIR
  MOV BX, OFFSET MSJ
  MOV AH, CAR_VIEJO
  MOV AL, CAR_NUEVO
  CALL REEMPLAZAR
  JMP INFORMAR
SEGUIR: INC BX
  INC CL
  INT 6
  JMP LEER

INFORMAR: CMP DL, 1
JNZ IMPRIMIR_NO
  MOV BX, OFFSET MSJ_SI
  MOV AL, OFFSET MSJ_NO - OFFSET MSJ_SI
  INT 7
  MOV BX, OFFSET MSJ
  MOV AL, 6
  INT 7
  JMP FIN_PROGRAM
IMPRIMIR_NO: MOV BX, OFFSET MSJ_NO
  MOV AL, OFFSET MSJ - OFFSET MSJ_NO
  INT 7
  
FIN_PROGRAM: INT 0
  END
